id: P006659
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W8LS20646
  title: ཐུམ་འབུའི་ནད་འགོག་བཅོས་ཤེས་བྱ།
  author: ''
  volumes:
    17969b4c57b04bbb8294684f6aa21b01:
      image_group_id: I8LS20648
      title: ''
      volume_number: 1
      total_pages: 122
      base_file: v001.txt
