id: P006659
initial_creation_type: ocr
source_metadata:
  id: bdr:W8LS20646
  title: ཐུམ་འབུའི་ནད་འགོག་བཅོས་ཤེས་བྱ།
  author: ''
  volumes:
    17969b4c57b04bbb8294684f6aa21b01:
      image_group_id: I8LS20648
      title: ''
      volume_number: 1
      total_pages: 122
